const BOOK_GENRES = [
  'Art & Design',
  'Biography',
  'Business',
  'Children's Books',
  'Coding & Programming',
  'Comics & Graphic Novels',
  'Cooking & Food',
  'Crafts & Hobbies',
  'Creativity',
  'Education',
  'Entrepreneurship',
  'Fantasy',
  'Fiction',
  'Finance',
  'Freelancing',
  'Health & Fitness',
  'History',
  'Horror',
  'Language Learning',
  'Leadership',
  'Lifestyle',
  'Marketing',
  'Memoir',
  'Mindset & Motivation',
  'Mystery',
  'Parenting & Family',
  'Personal Development',
  'Philosophy',
  'Poetry',
  'Politics',
  'Productivity',
  'Psychology',
  'Religion & Spirituality',
  'Romance',
  'Sales',
  'Science',
  'Science Fiction',
  'Self-Help',
  'Social Media',
  'Technology',
  'Thriller',
  'Travel',
  'Wellness',
  'Women's Interests',
  'Writing'
].sort((a, b) => a.localeCompare(b));

function getBookGenres() {
  return [...BOOK_GENRES];
}
