const BOOK_GENRES = [
  'Art & Design',
  'Biography',
  'Business',
  'Children',
  'Comics & Graphic Novels',
  'Cooking & Food',
  'Crafts & Hobbies',
  'Education',
  'Entrepreneurship',
  'Fantasy',
  'Fiction',
  'Finance',
  'Health & Fitness',
  'History',
  'Horror',
  'Humor',
  'Language Learning',
  'Lifestyle',
  'Marketing',
  'Memoir',
  'Mystery',
  'Non-Fiction',
  'Parenting',
  'Personal Development',
  'Philosophy',
  'Poetry',
  'Politics',
  'Productivity',
  'Psychology',
  'Relationships',
  'Religion & Spirituality',
  'Romance',
  'Science',
  'Science Fiction',
  'Self-Help',
  'Technology',
  'Thriller',
  'Travel',
  'Writing',
].sort((a, b) => a.localeCompare(b));

function getBookGenres() {
  return [...BOOK_GENRES];
}
