const BOOK_GENRES = [
  'Art & Design',
  'Biography',
  'Business',
  'Children',
  'Comics & Graphic Novels',
  'Cooking & Food',
  'Crafts & Hobbies',
  'Education',
  'Entrepreneurship',
  'Fantasy',
  'Fiction',
  'Finance',
  'Health & Fitness',
  'History',
  'Horror',
  'Humor',
  'Language Learning',
  'Lifestyle',
  'Marketing',
  'Memoir',
  'Mystery',
  'Non-Fiction',
  'Parenting',
  'Personal Development',
  'Philosophy',
  'Poetry',
  'Politics',
  'Productivity',
  'Psychology',
  'Relationships',
  'Religion & Spirituality',
  'Romance',
  'Science',
  'Science Fiction',
  'Self-Help',
  'Technology',
  'Thriller',
  'Travel',
  'Writing',
].sort((a, b) => a.localeCompare(b));

const GENRE_ALIASES = {
  'self development': 'Personal Development',
  'self-development': 'Personal Development',
  'personal development': 'Personal Development',
  'personal growth': 'Personal Development',
  'self help': 'Self-Help',
  'self-help': 'Self-Help',
  'fiction': 'Fiction',
  'sci fi': 'Science Fiction',
  'sci-fi': 'Science Fiction',
  'science fiction': 'Science Fiction',
  'mystery': 'Mystery',
  'thriller': 'Thriller',
  'romance': 'Romance',
  'business': 'Business',
  'finance': 'Finance',
  'marketing': 'Marketing',
  'productivity': 'Productivity',
  'technology': 'Technology',
  'health': 'Health & Fitness',
  'health and fitness': 'Health & Fitness',
  'psychology': 'Psychology',
  'education': 'Education',
  'travel': 'Travel',
  'cooking': 'Cooking & Food',
  'history': 'History',
  'biography': 'Biography',
  'memoir': 'Memoir',
  'poetry': 'Poetry',
  'writing': 'Writing',
  'childrens books': 'Children',
  "children's books": 'Children',
  'children': 'Children',
  'parenting': 'Parenting',
  'parenting & family': 'Parenting',
  'non fiction': 'Non-Fiction',
  'non-fiction': 'Non-Fiction',
  'humour': 'Humor',
  'humor': 'Humor',
  'art': 'Art & Design',
  'art and design': 'Art & Design',
  'crafts': 'Crafts & Hobbies',
  'language': 'Language Learning',
};

function normalizeGenre(value) {
  const raw = String(value || '').trim();
  if (!raw) return '';
  const lowered = raw.toLowerCase();
  if (GENRE_ALIASES[lowered]) return GENRE_ALIASES[lowered];
  const direct = BOOK_GENRES.find((genre) => genre.toLowerCase() === lowered);
  return direct || '';
}

module.exports = { BOOK_GENRES, normalizeGenre };
